### PR TITLE
CD-191077 wktemp* files are not deleted and moved defer before return

### PR DESCRIPTION
**Pull request by revathi-murali**
## JIRA

[Main JIRA](https://coupadev.atlassian.net/browse/CD-191077)

## Reviewers

- [ ] @priyankatapar 

## Summary of change

-  Changed the path for `wktemp*` files
-  Also moved the defer of removal of files before return

### CODE REVIEW

**Comment by priyankatapar** [comment]
Good catch! How did you come to know about this issue?

**Comment by priyankatapar** [comment]
👍

**Comment by revathi-murali** [comment]
> Good catch! How did you come to know about this issue?

Saw that temp files were not deleted when I was debugging the memory issue.

**Comment by revathi-murali** [comment]
[lockit v4.9.3] merged via Lockit CLI on 2020-03-19 13:24:06.984577 +0530 IST m=+7.190814833

**Pull request merged**
